# Cache definition for dynamic requests
proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=dynamic_cache:10m max_size=1g;

upstream gunicorn_app {
    server 127.0.0.1:8000;
}

server {
    listen 80;
    server_name localhost;
    gzip on;
    gzip_types text/plain text/css application/javascript image/*;

    # Routing for uploads directory
    location /uploads/ {
        alias /home/ivan/projects/vk-education/2026-VK-EDU-Web-11-Ovchinnikov-I/uploads/;
        expires max;
    }

    # Routing for static files with specific extensions
    location ~* \.(js|css|jpeg|png|jpg)$ {
        root /home/ivan/projects/vk-education/2026-VK-EDU-Web-11-Ovchinnikov-I/static;
        expires max;
    }

    # Proxy all other requests to Gunicorn with caching
    location / {
        proxy_pass http://gunicorn_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        proxy_cache dynamic_cache;
        proxy_cache_valid 200 302 60m;
        proxy_cache_valid 404 1m;
    }
}
