services:
  db:
    image: postgres:15
    container_name: IvanAsk_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - common

  redis:
    image: redis:7-alpine
    container_name: IvanAsk_redis
    restart: unless-stopped
    networks:
      - common

  app:
    container_name: IvanAsk
    build:
      context: .
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - django_media:/app/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - common
    depends_on:
      - db
      - redis

  worker:
    container_name: IvanAsk_worker
    build:
      context: .
    restart: unless-stopped
    command: celery -A application worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - common
    depends_on:
      - db
      - redis

  beat:
    container_name: IvanAsk_beat
    build:
      context: .
    restart: unless-stopped
    command: celery -A application beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - common
    depends_on:
      - db
      - redis

  centrifugo:
    image: centrifugo/centrifugo:v5
    container_name: IvanAsk_centrifugo
    restart: unless-stopped
    ports:
      - "8010:8000"
    volumes:
      - ./centrifugo_config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    networks:
      - common

volumes:
  django_media:
  db-data:

networks:
  common:
    driver: bridge
