services:
  app:
    container_name: IvanAsk
    build:
      context: .
    restart: unless-stopped
    command: >
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - django_media:/app/media
    ports:
      - "8000:8000"

volumes:
  django_media:
