# Generated by Django 6.0.4 on 2026-05-26 22:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='answer_cnt',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество ответов'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to=core.models.profile_photo_path, verbose_name='Аватар'),
        ),
    ]
